Repository washcarnewcar/api.washcar.me-spring-server, pull requests merged in 2023-02, with the labels that each got.

#5 Feature/#2 이슈 pr 템플릿을 생성한다
  .github/ISSUE_TEMPLATE/이슈-템플릿-입니다.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📜 docs

#6 test: MemberRepositoryTest 작성
  src/test/java/me/washcar/wcnc/domain/member/MemberTestHelper.java
  src/test/java/me/washcar/wcnc/domain/member/dao/MemberRepositoryTest.java
Labels: ✅ test

#8 test: MemberService 테스트 코드 작성
  src/test/java/me/washcar/wcnc/domain/member/MemberTestHelper.java
  src/test/java/me/washcar/wcnc/domain/member/service/MemberServiceTest.java
Labels: ✅ test

#11 fix: 빌드 도중의 hibernate deprecated setting 경고 해결
  src/main/resources/application.yml
Labels: 🐞 bug

#10 refactor: domain entity 의 package structure 개선
  src/main/java/me/washcar/wcnc/domain/car/brand/dao/BrandRepository.java
  src/main/java/me/washcar/wcnc/domain/car/brand/entity/Brand.java
  src/main/java/me/washcar/wcnc/domain/car/model/dao/ModelRepository.java
  src/main/java/me/washcar/wcnc/domain/car/model/entity/Model.java
  src/main/java/me/washcar/wcnc/domain/member/dao/MemberRepository.java
  src/main/java/me/washcar/wcnc/domain/member/entity/Member.java
  src/main/java/me/washcar/wcnc/domain/member/service/MemberService.java
  src/main/java/me/washcar/wcnc/domain/reservation/entity/Reservation.java
  src/main/java/me/washcar/wcnc/domain/store/Store.java
  src/main/java/me/washcar/wcnc/domain/store/entity/Location.java
  src/main/java/me/washcar/wcnc/domain/store/entity/Store.java
  src/main/java/me/washcar/wcnc/domain/store/entity/image/StoreImage.java
  src/main/java/me/washcar/wcnc/domain/store/entity/menu/StoreMenu.java
  src/main/java/me/washcar/wcnc/domain/store/entity/operation/StoreOperationHoliday.java
  src/main/java/me/washcar/wcnc/domain/store/entity/operation/StoreOperationHour.java
  src/test/java/me/washcar/wcnc/domain/member/MemberTestHelper.java
  src/test/java/me/washcar/wcnc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/me/washcar/wcnc/domain/member/service/MemberServiceTest.java
Labels: ⚙ refactor

#9 Feature/auth
  build.gradle
  src/main/java/me/washcar/wcnc/domain/auth/KakaoMember.java
  src/main/java/me/washcar/wcnc/domain/auth/OAuth2Member.java
  src/main/java/me/washcar/wcnc/domain/auth/SignupToken.java
  src/main/java/me/washcar/wcnc/domain/auth/controller/AuthController.java
  src/main/java/me/washcar/wcnc/domain/auth/dao/SignupTokenRepository.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/LoginDto.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/SignupDto.java
  src/main/java/me/washcar/wcnc/domain/auth/service/AuthService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/CookieService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/JwtService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/MemberDetailsService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/OAuth2MemberService.java
  src/main/java/me/washcar/wcnc/domain/member/MemberAuthenticationType.java
  src/main/java/me/washcar/wcnc/domain/member/MemberRole.java
  src/main/java/me/washcar/wcnc/domain/member/OAuth.java
  src/main/java/me/washcar/wcnc/domain/member/controller/MemberController.java
  src/main/java/me/washcar/wcnc/domain/member/dao/MemberRepository.java
  src/main/java/me/washcar/wcnc/domain/member/dao/OAuthRepository.java
  src/main/java/me/washcar/wcnc/domain/member/dto/response/MemberDto.java
  src/main/java/me/washcar/wcnc/domain/member/entity/Member.java
  src/main/java/me/washcar/wcnc/domain/member/service/MemberService.java
  src/main/java/me/washcar/wcnc/global/configuration/security/CorsConfiguration.java
  src/main/java/me/washcar/wcnc/global/configuration/security/SecurityConfiguration.java
  src/main/java/me/washcar/wcnc/global/definition/Regex.java
  src/main/java/me/washcar/wcnc/global/definition/RegexMessage.java
  src/main/java/me/washcar/wcnc/global/entity/UuidEntity.java
  src/main/java/me/washcar/wcnc/global/error/ApplicationError.java
  src/main/java/me/washcar/wcnc/global/error/ApplicationException.java
  src/main/java/me/washcar/wcnc/global/error/BusinessError.java
  src/main/java/me/washcar/wcnc/global/error/ExceptionAdvice.java
  src/main/java/me/washcar/wcnc/global/filter/JwtAuthorizationFilter.java
  src/main/java/me/washcar/wcnc/global/handler/JwtAccessDeniedHandler.java
  src/main/java/me/washcar/wcnc/global/handler/JwtAuthenticationEntryPoint.java
  src/main/java/me/washcar/wcnc/global/handler/OAuth2FailureHandler.java
  src/main/java/me/washcar/wcnc/global/handler/OAuth2SuccessHandler.java
  src/main/java/me/washcar/wcnc/global/utility/AuthorizationHelper.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/me/washcar/wcnc/domain/member/MemberTestHelper.java
  src/test/java/me/washcar/wcnc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/me/washcar/wcnc/domain/member/service/MemberServiceTest.java
Labels: 🎉 feature

#12 refactor: 빌더 어노테이션을 위한 생성자와 request dto의 unused 워닝 해제
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/LoginDto.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/SignupDto.java
  src/main/java/me/washcar/wcnc/domain/member/dto/request/MemberPatchRequestDto.java
  src/main/java/me/washcar/wcnc/domain/member/entity/Member.java
  src/main/java/me/washcar/wcnc/domain/store/entity/image/StoreImage.java
Labels: ⚙ refactor

#14 fix: loginId 중복체크 반대로 작동하는 버그 수정, 시큐리티 설정 수정 / refactor: 상세 설명 참조
  IntelliJ-code-formatter.xml
  src/main/java/me/washcar/wcnc/domain/auth/controller/AuthController.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/LoginDto.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/request/SignupDto.java
  src/main/java/me/washcar/wcnc/domain/auth/service/AuthService.java
  src/main/java/me/washcar/wcnc/global/configuration/security/SecurityConfiguration.java
  src/main/java/me/washcar/wcnc/global/error/BusinessError.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🐞 bug, ⚙ refactor

#13 refactor: Member 도메인 리팩토링
  src/main/java/me/washcar/wcnc/domain/member/controller/MemberController.java
  src/main/java/me/washcar/wcnc/domain/member/service/MemberService.java
  src/main/java/me/washcar/wcnc/global/definition/Regex.java
  src/main/java/me/washcar/wcnc/global/definition/RegexMessage.java
  src/test/java/me/washcar/wcnc/domain/member/service/MemberServiceTest.java
Labels: ⚙ refactor

#15 refactor: 로그인 로직 리팩토링
  src/main/java/me/washcar/wcnc/domain/auth/KakaoMember.java
  src/main/java/me/washcar/wcnc/domain/auth/OAuth2Member.java
  src/main/java/me/washcar/wcnc/domain/auth/adapter/AuthenticationAdapter.java
  src/main/java/me/washcar/wcnc/domain/auth/adapter/KakaoAdapterImpl.java
  src/main/java/me/washcar/wcnc/domain/auth/adapter/LoginIdAdapterImpl.java
  src/main/java/me/washcar/wcnc/domain/auth/adapter/OAuth2Adapter.java
  src/main/java/me/washcar/wcnc/domain/auth/controller/AuthController.java
  src/main/java/me/washcar/wcnc/domain/auth/dto/response/MemberMeDto.java
  src/main/java/me/washcar/wcnc/domain/auth/service/AuthService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/CookieService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/JwtService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/MemberDetailsService.java
  src/main/java/me/washcar/wcnc/domain/auth/service/OAuth2MemberService.java
  src/main/java/me/washcar/wcnc/domain/member/dao/OAuthRepository.java
  src/main/java/me/washcar/wcnc/domain/member/entity/Member.java
  src/main/java/me/washcar/wcnc/domain/member/entity/OAuth.java
  src/main/java/me/washcar/wcnc/global/error/BusinessError.java
  src/main/java/me/washcar/wcnc/global/handler/OAuth2SuccessHandler.java
Labels: ⚙ refactor

#17 Feature/store api
  src/main/java/me/washcar/wcnc/domain/member/entity/Member.java
  src/main/java/me/washcar/wcnc/domain/store/controller/StoreController.java
  src/main/java/me/washcar/wcnc/domain/store/dao/StoreRepository.java
  src/main/java/me/washcar/wcnc/domain/store/dto/request/StorePatchRequestDto.java
  src/main/java/me/washcar/wcnc/domain/store/dto/request/StoreRequestDto.java
  src/main/java/me/washcar/wcnc/domain/store/dto/response/StoreDto.java
  src/main/java/me/washcar/wcnc/domain/store/entity/Location.java
  src/main/java/me/washcar/wcnc/domain/store/entity/Store.java
  src/main/java/me/washcar/wcnc/domain/store/service/StoreService.java
  src/main/java/me/washcar/wcnc/global/configuration/security/SecurityConfiguration.java
  src/main/java/me/washcar/wcnc/global/error/ApplicationError.java
  src/main/java/me/washcar/wcnc/global/error/BusinessError.java
  src/main/java/me/washcar/wcnc/global/utility/AuthorizationHelper.java
  src/test/java/me/washcar/wcnc/domain/store/StoreTestHelper.java
  src/test/java/me/washcar/wcnc/domain/store/dao/StoreRepositoryTest.java
  src/test/java/me/washcar/wcnc/domain/store/service/StoreServiceTest.java
Labels: 🎉 feature, ✅ test

#19 Refactor AuthorizationHelper.java
  src/main/java/me/washcar/wcnc/global/utility/AuthorizationHelper.java
Labels: ⚙ refactor
